### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by kwlzn** [minrk/pexnb#2]
It'd be cool to have some basic test coverage for `pexnb.py` to keep things functional as both jupyter and pex change over time. I wonder if there is any prior art for testing custom `KernelSpecManager` implementations end to end?

**Comment by minrk** [comment]
Good idea. Basic tests are added in #3. It's not tested end-to-end yet (in that the tests don't start a notebook and then launch kernels via the REST API), but it's everything but.
